StableDiffusion:
    model_id: CompVis/stable-diffusion-v1-4

TextualInversion:
    model_id: CompVis/stable-diffusion-v1-4
    learning_rate: 0.0005
    scale_lr: true
    max_train_steps: 2000
    save_steps: 250
    batch_size: 4
    gradient_accumulation_steps: 1
    gradient_checkpointing: true
    mixed_precision: fp16
    seed: 42
    output_dir: data/output/textual_inversion

LoRA:
    model_id: CompVis/stable-diffusion-v1-4
    gradient_accumulation_steps: 1
    mixed_precision: fp16
    batch_size: 4
    num_train_epochs: 100
    learning_rate: 0.0005
    lr_warmup_steps: 0
    max_train_steps: 2000
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: 0.00000001
    lr_scheduler: constant  # ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
    noise_offset: 0
    prediction_type: null  # Choose between 'epsilon' or 'v_prediction' or leave `None`
    max_grad_norm: 1.0
    checkpointing_steps: 500
    output_dir: data/output/lora
    validation_prompt: null
    validation_epochs: 1
    num_validation_images: 4
    seed: 42
    resolution: 512
    center_crop: false
    random_flip: true

StableDiffusionXLLoRA:
    model_id: stabilityai/stable-diffusion-xl-base-1.0
    vae_model_id: madebyollin/sdxl-vae-fp16-fix
    instance_prompt: a photo of a single sks skin lesion in the skin of a person
    mixed_precision: fp16
    resolution: 1024
    batch_size: 2
    num_train_epochs: 100
    gradient_accumulation_steps: 2
    gradient_checkpointing: true
    enable_xformers_memory_efficient_attention: true
    use_8bit_adam: true
    train_text_encoder: false
    learning_rate: 0.0001
    lr_warmup_steps: 0
    max_train_steps: 500
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: 0.00000001
    lr_scheduler: constant  # ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
    noise_offset: 0
    rank: 4
    crops_coords_top_left_h: 0
    crops_coords_top_left_w: 0
    prediction_type: null  # Choose between 'epsilon' or 'v_prediction' or leave `None`
    max_grad_norm: 1.0
    checkpointing_steps: 100
    output_dir: data/output/sdxl_lora
    validation_prompt: null
    validation_epochs: 1
    num_validation_images: 4
    seed: 42
    resolution: 512
    center_crop: false
    random_flip: true
    n_class_images: 100
    lr_num_cycles: 1
    lr_power: 1.0
    resume_from_checkpoint: null  # Path of the checkpoint to resume from
