StableDiffusion:
    model_id: CompVis/stable-diffusion-v1-4


TextualInversion:
    model_id: CompVis/stable-diffusion-v1-4
    learning_rate: 0.0005
    scale_lr: true
    max_train_steps: 4000
    save_steps: 250
    batch_size: 4
    gradient_accumulation_steps: 1
    gradient_checkpointing: true
    mixed_precision: fp16
    seed: 42
    output_dir: data/output/textual_inversion


LoRA:
    model_id: CompVis/stable-diffusion-v1-4
    gradient_accumulation_steps: 1
    mixed_precision: fp16
    batch_size: 4
    num_train_epochs: 100
    learning_rate: 0.0005
    lr_warmup_steps: 0
    max_train_steps: 4000
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    adam_weight_decay: 0.01
    adam_epsilon: 0.00000001
    lr_scheduler: constant  # ["linear", "cosine", "cosine_with_restarts", "polynomial", "constant", "constant_with_warmup"]
    noise_offset: 0
    prediction_type: null  # Choose between 'epsilon' or 'v_prediction' or leave `None`
    max_grad_norm: 1.0
    checkpointing_steps: 250
    output_dir: data/output/lora
    validation_prompt: null
    validation_epochs: 1
    num_validation_images: 4
    seed: 42
    resolution: 512
    center_crop: false
    random_flip: true


Clustering:
    model_id: efficientnet-b0
    batch_size: 16
    epsilon: 0.1
    min_samples: 5
    metric: euclidean
